{% set version = "5.16.1" %}
{% set name = "pymc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 00eff0ccc7c06029aab2c580524f101e922315d3937a82d116b842065a120847

build:
  number: 0
  skip: True  # [py<=310]
  script:
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.15.0
    - arviz >=0.13.0
    - cachetools >=4.2.1
    - cloudpickle
    - pandas >=0.24.0
    - pytensor >=2.23,<2.24
      # Reverting scipy to <1.13 due to pymc import failure that was caused due to older version of arviz
    - scipy >=1.4.1,<1.13
    - rich >=13.7.1
    - typing-extensions >=3.7.4
    - threadpoolctl >=3.1.0,<4.0.0

test:
  source_files:
    - tests
  imports:
    - pymc
    - pymc.backends
    - pymc.distributions
    - pymc.gp
    - pymc.step_methods
    - pymc.tuning
    - pymc.variational
    - pymc.ode
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests/model/test_core.py

about:
  home: https://www.pymc.io/welcome.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'PyMC: Bayesian Stochastic Modelling in Python'

  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain
    Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core
    sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence
    diagnostics.
  doc_url: https://www.pymc.io/projects/docs/en/stable/api.html
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf
