{% set version = "5.6.0" %}

package:
  name: pymc
  version: {{ version }}

source:
  url: https://github.com/pymc-devs/pymc/archive/v{{version}}.tar.gz
  sha256: a09b11a0ae9a56a6f57b9b89f161d06b1d49b7d80a84311eba4376f2a32b5d0f

build:
  number: 0
  # skip because arviz is not supported for py38
  skip: True  # [py<39]
  script:
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - export LDFLAGS="$LDFLAGS -shared"  # [linux]
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - mkl-devel  {{ mkl }}      # [blas_impl == "mkl"]
    - openblas-devel {{ openblas }}  # [blas_impl == "openblas"]
    - numpy {{ numpy }}
    - cachetools 4.2.2
    - cloudpickle
    - fastprogress 1.0.0
    - pandas 1.5.3
    - typing-extensions 4.6.3
  run:
    - python
    - numpy >=1.15.0
    - arviz >=0.13.0
    - cachetools >=4.2.1
    - cloudpickle
    - fastprogress >=0.2.0
    - pandas >=0.24.0
    - pytensor >=2.12.0,<2.13
    - scipy >=1.4.1
    - typing-extensions >=3.7.4

test:
  imports:
    - pymc
    - pymc.database
    - pymc.examples
    - pymc.gp
    - pymc.gp.cov_funs
    - pymc.Container_values
    - pymc.LazyFunction
    - pymc.flib
    - pymc.gp.cov_funs.distances
    - pymc.gp.cov_funs.isotropic_cov_funs
    - pymc.gp.incomplete_chol
    - pymc.gp.linalg_utils

about:
  home: https://www.pymc.io/welcome.html
  license: AFL-3.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'PyMC: Bayesian Stochastic Modelling in Python'

  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain
    Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core
    sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence
    diagnostics.
  doc_url: https://www.pymc.io/projects/docs/en/stable/api.html
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf
