{% set version = "5.23.0" %}
{% set name = "pymc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-devs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d27f49167f054b707eaa70b02f45033c8a98c1e1ea427ec82bb27fc24f1bafd
  patches:
    - 0001-patch-out-numpyro.patch  # [py>=312]

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports:
    - numpy
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - versioneer 0.29
    - toml
  run:
    - python
    - numpy >=1.25.0
    - arviz >=0.13.0
    - cachetools >=4.2.1
    - cloudpickle
    - pandas >=0.24.0
    - pytensor >=2.31.2,<2.32
    # scipy was limited to <1.13 due to pymc import failure that was caused due to older version of arviz
    - scipy >=1.4.1, <1.13
    - rich >=13.7.1
    - typing-extensions >=3.7.4
    - threadpoolctl >=3.1.0,<4.0.0

{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + "test_numpyro_nuts_kwargs_are_used" %}  # [py>=312]
# skip tests that depend on blackjax
{% set tests_to_skip = tests_to_skip + " or test_transform_samples or test_deterministic_samples or test_initvals_without_jitter or test_idata_kwargs" %}
{% set tests_to_skip = tests_to_skip + " or test_seeding or test_idata_contains_stats or test_convergence_warnings" %}


# skip tests for py313 since some dependencies are missing for numpy
# also skip tests on osx-x86_64 because they stall
test:  #[py<313 and not (osx and x86_64)]
  source_files:  #[py<313 and not (osx and x86_64)]
    - tests  #[py<313 and not (osx and x86_64)]
  imports:  #[py<313 and not (osx and x86_64)]
    - pymc  #[py<313 and not (osx and x86_64)]
    - pymc.backends  #[py<313 and not (osx and x86_64)]
    - pymc.distributions  #[py<313 and not (osx and x86_64)]
    - pymc.gp  #[py<313 and not (osx and x86_64)]
    - pymc.step_methods  #[py<313 and not (osx and x86_64)]
    - pymc.tuning  #[py<313 and not (osx and x86_64)]
    - pymc.variational  #[py<313 and not (osx and x86_64)]
    - pymc.ode  #[py<313 and not (osx and x86_64)]
  requires:  #[py<313 and not (osx and x86_64)]
    - pip  #[py<313 and not (osx and x86_64)]
    - pytest  #[py<313 and not (osx and x86_64)]
    - jax  #[py<313 and not (osx and x86_64)]
    - zarr  #[py<313 and not (osx and x86_64)]
    - graphviz  #[py<313 and not (osx and x86_64)]
    - sfe1ed40::numpyro  # [py<312 and not (osx and x86_64)]
    # to avoid error about np.PINF, numpy must be <2, so on py313 it's missing for linux aarch64
    - numpy >=1.25.0  #[py<313 and not (osx and x86_64)]
  commands:  #[py<313 and not (osx and x86_64)]
    # skip pip check because it fails due to asciitree which is pulled by other test requirements
    #- pip check
    # skip these tests because they take too long to run
    - pytest -k "not ({{ tests_to_skip }})" -v tests/model tests/ode tests/sampling tests/smc tests/stats tests/step_methods tests/tuning tests/variational test_data.py test_func_utils.py test_initial_point.py test_math.py test_model_graph.py test_printing.py test_pytensorf.py test_testing.py test_util.py  # [py==312 and not (osx and x86_64)]
    - pytest -v tests/model tests/ode tests/sampling tests/smc tests/stats tests/step_methods tests/tuning tests/variational tests/test_data.py tests/test_func_utils.py tests/test_initial_point.py tests/test_math.py tests/test_model_graph.py tests/test_printing.py tests/test_pytensorf.py tests/test_testing.py tests/test_util.py  # [py<312 and not (osx and x86_64)]

about:
  home: https://www.pymc.io/welcome.html
  license: Apache-2.0 AND MIT
  license_family: OTHER
  license_file: LICENSE
  summary: PyMC - Bayesian Stochastic Modelling in Python
  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain
    Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core
    sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence
    diagnostics.
  doc_url: https://www.pymc.io/projects/docs/en/stable/api.html
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf