{% set name = "pymc" %}
{% set version = "5.23.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-devs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d27f49167f054b707eaa70b02f45033c8a98c1e1ea427ec82bb27fc24f1bafd

build:
  number: 1
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports:
    - numpy
    - libstdcxx-ng

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - versioneer 0.29
    - toml
  run:
    - python
    - numpy >=1.25.0
    # rviz >=0.13,<0.18 is broken, so we need to use >=0.18.0, more details:
    # https://discourse.pymc.io/t/importerror-cannot-import-name-gaussian-from-scipy-signal/14170/7
    - arviz >=0.18.0
    - cachetools >=4.2.1
    - cloudpickle
    - pandas >=0.24.0
    - pytensor >=2.31.2,<2.32
    - scipy >=1.4.1
    - rich >=13.7.1
    - typing-extensions >=3.7.4
    - threadpoolctl >=3.1.0,<4.0.0

{% set tests_to_skip = "" %}
# skip tests that depend on blackjax
{% set tests_to_skip = tests_to_skip + "test_transform_samples or test_deterministic_samples or test_initvals_without_jitter or test_idata_kwargs" %}
{% set tests_to_skip = tests_to_skip + " or test_seeding or test_idata_contains_stats or test_convergence_warnings" %}
# skip tests that depend on graphviz because of missing binaries
{% set tests_to_skip = tests_to_skip + " or test_graphviz or test_checks_formatting or test_unknown_node_type or test_custom_node_formatting_networkx or test_custom_node_formatting_graphviz" %}
# skip tests that depend on flapack failed import on macos
{% set tests_to_skip = tests_to_skip + " or test_convergence_checks or test_return_datatype or test_kernel_kwargs or test_marginal_likelihood or test_parallel_custom" %}  # [osx]
# skip tests depending on numpyro (only present in private channel)
{% set tests_to_skip = tests_to_skip + " or test_numpyro_nuts_kwargs_are_used"%}
# skip tests that have error
# Loop fusion failed because of following error:
# E UserWarning: Loop fusion failed because the resulting node would exceed the kernel argument limit.
{% set tests_to_skip = tests_to_skip + " or test_fit_start or test_fit_data or test_fit_fn_text or test_fit_oo"%}
# skip tests that have error in concurrent.futures
#  _pickle.PicklingError: Can't pickle <class '_flapack.error'>: import of module '_flapack' failed (non-critical error)
{% set tests_to_skip = tests_to_skip + " or test_parallel_custom or test_marginal_likelihood or test_kernel_kwargs or test_return_datatype or test_convergence_checks"%}  # [linux]
# skip test that fails with cast error on win-64 (non-critical error)
{% set tests_to_skip = tests_to_skip + " or test_inputs_preserved"%}  # [win]

# also skip tests on osx-x86_64 because they stall on CI
test:  #[py<313 and not (osx and x86_64)]
  source_files:  #[not (osx and x86_64)]
    - tests  #[not (osx and x86_64)]
  imports:  #[not (osx and x86_64)]
    - pymc  #[not (osx and x86_64)]
    - pymc.backends  #[not (osx and x86_64)]
    - pymc.distributions  #[not (osx and x86_64)]
    - pymc.gp  #[not (osx and x86_64)]
    - pymc.step_methods  #[not (osx and x86_64)]
    - pymc.tuning  #[not (osx and x86_64)]
    - pymc.variational  #[not (osx and x86_64)]
    - pymc.ode  #[not (osx and x86_64)]
  commands:  #[not (osx and x86_64)]
    # skip pip check because it fails due to asciitree which is pulled by other test requirements
    #- pip check
    # skip the tests because they take too long to run, though they all pass on each platform
    #- pytest -k "not ({{ tests_to_skip }})" -v tests/model tests/ode tests/smc tests/stats tests/step_methods tests/tuning tests/variational  # [py==312 and not (osx and x86_64)]
    #- pytest -k "not ({{ tests_to_skip }})" -v tests/test_data.py tests/test_func_utils.py tests/test_initial_point.py tests/test_math.py tests/test_model_graph.py tests/test_printing.py tests/test_pytensorf.py tests/test_testing.py tests/test_util.py  # [py<312 and not (osx and x86_64)]
  requires:  #[not (osx and x86_64)]
    - pip  #[not (osx and x86_64)]
    - pytest  #[not (osx and x86_64)]
    - jax  #[not (osx and x86_64)]
    - zarr  #[not (osx and x86_64)]
    # to avoid error about np.PINF, numpy must be <2, so on py313 it's missing for linux aarch64
    - numpy >=1.25.0  #[not (osx and x86_64)]

about:
  home: https://www.pymc.io/welcome.html
  license: Apache-2.0 AND MIT
  license_family: OTHER
  license_file: LICENSE
  summary: PyMC - Bayesian Stochastic Modelling in Python
  description: |
    PyMC is a python module that implements Bayesian statistical models and fitting algorithms, including Markov chain
    Monte Carlo. Its flexibility and extensibility make it applicable to a large suite of problems. Along with core
    sampling functionality, PyMC includes methods for summarizing output, plotting, goodness-of-fit and convergence
    diagnostics.
  doc_url: https://www.pymc.io/projects/docs/en/stable/api.html
  dev_url: https://github.com/pymc-devs/pymc

extra:
  recipe-maintainers:
    - fonnesbeck
    - ocefpaf
