travis:
  secure:
    BINSTAR_TOKEN: n8tMY0yAS2nvgxHjpDWao7YHHMm1i2QVQlkWi/metunx6h8yM8i0/2h2a0brNKZSztsaOosyiDpgwV5HH5++6im8tXhGCruoNMr1ZKEAXRFrnkvYX4+ZJUpuH4jgmd1IRB7OzMkPNyTgQNNczTgumoevDMY1agOrUD8hLWuNlhp8LGfY67Y4RfRY8F96/trTX2l/bJ6+HF+Txt2LvD+4BM4fsbZi/VJekiqy6AlaLeZWpjvHdcMlmZ1WVU21qqqaSB7aC62YOD38gfW/zlutLQoiO700eYNwK+HoMMFfzFnb+L9aJb8ZONGP3ds0zohEqT5GqDugHamRfT54fTFRRGSfGxHvGH9y7DQnIywBh1rDuNuP+6MWEjySkJsdLmPQbXFCHw3T0reZwXE1kDm8QITBLowp09PyD7NgFNztBdwIOj+ibBliGo/OoXW5HjKGiN6kDC1fOEqspsLpi68jUyYAfECl0b32Ie3e2eH2QnooWuahzk7m3Izry1C8S9Pj3R5SDD7w+8Szpv8ChcWdKsMFcyQta+H1rQku2q0Og5xH5MJRaVOIISEv6gwoej0vuIdA34gL5zEezhC06IXCvYeTn+hJQPIanybB0zH8tIJ8CXWq7lbxMgUlR63nRtJcyKRnp2a7qSrz7v06IEMu/DVXoHYkc2i5FEuV4Mw5Zh8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
